packages: []

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  esbuild: true
  workerd: true

minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260811.1'
  - miniflare@5.20260804.0-alpha || 5.20260908.0-alpha
  - wrangler@4.120.1 || 4.130.0
  - '@cloudflare/vitest-plugin@1.1.6'
