import {
  assertValidModelCatalog,
  type ModelDefinition,
} from "@/lib/model-catalog"

const VERIFIED_AT = "2026-09-09"
const CLOUDFLARE_FAL_DOCS =
  "https://developers.cloudflare.com/ai-gateway/usage/providers/fal/"

function verified(...docs: string[]) {
  return { lastVerifiedAt: VERIFIED_AT, docs } as const
}

export const MODEL_CATALOG = assertValidModelCatalog([
  // Text / reasoning / vision -------------------------------------------------
  {
    key: "@cf/zai-org/glm-5.3-flash",
    upstreamModelId: "@cf/zai-org/glm-5.3-flash",
    name: "GLM 5.3 Flash",
    provider: "zai-org",
    catalogSource: "workers-ai",
    transport: "workers-binding",
    protocol: "workers-ai",
    lifecycle: "launch",
    roles: ["balanced", "fast", "value", "workers-hosted"],
    inputs: ["text", "image"],
    outputs: ["text"],
    capabilities: [
      "chat",
      "reasoning",
      "vision",
      "tool-calling",
      "structured-output",
    ],
    representations: [{ artifact: "text", format: "markdown" }],
    execution: { result: "immediate", streaming: true },
    tools: { appTools: true, parallelCalls: true },
    reasoning: { supported: true, controls: ["effort"] },
    continuation: { mode: "none" },
    limits: { contextTokens: 1_048_576 },
    billingClass: "value",
    accessClass: "public",
    zeroDataRetention: "unknown",
    parameterSchemaRef:
      "https://developers.cloudflare.com/workers-ai/models/glm-5.3-flash/",
    verification: verified(
      "https://developers.cloudflare.com/workers-ai/models/glm-5.3-flash/"
    ),
  },
  {
    key: "openai/gpt-5.6-terra",
    upstreamModelId: "openai/gpt-5.6-terra",
    name: "GPT-5.6 Terra",
    provider: "openai",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "responses",
    lifecycle: "launch",
    roles: ["balanced"],
    inputs: ["text"],
    outputs: ["text"],
    capabilities: ["chat", "reasoning", "tool-calling", "structured-output"],
    representations: [{ artifact: "text", format: "markdown" }],
    execution: { result: "immediate", streaming: true },
    tools: { appTools: true, nativeTools: ["web-search"] },
    reasoning: { supported: true, controls: ["effort"] },
    continuation: { mode: "provider-state" },
    limits: { contextTokens: 1_050_000 },
    billingClass: "standard",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/openai/gpt-5.6-terra/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/openai/gpt-5.6-terra/"
    ),
  },
  {
    key: "openai/gpt-5.6-sol",
    upstreamModelId: "openai/gpt-5.6-sol",
    name: "GPT-5.6 Sol",
    provider: "openai",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "responses",
    lifecycle: "launch",
    roles: ["frontier"],
    inputs: ["text"],
    outputs: ["text"],
    capabilities: ["chat", "reasoning", "tool-calling", "structured-output"],
    representations: [{ artifact: "text", format: "markdown" }],
    execution: { result: "immediate", streaming: true },
    tools: { appTools: true, nativeTools: ["web-search"] },
    reasoning: { supported: true, controls: ["effort"] },
    continuation: { mode: "provider-state" },
    limits: { contextTokens: 1_050_000 },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/openai/gpt-5.6-sol/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/openai/gpt-5.6-sol/"
    ),
  },
  {
    key: "anthropic/claude-sonnet-5",
    upstreamModelId: "anthropic/claude-sonnet-5",
    name: "Claude Sonnet 5",
    provider: "anthropic",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "messages",
    lifecycle: "launch",
    roles: ["balanced"],
    inputs: ["text"],
    outputs: ["text"],
    capabilities: ["chat", "reasoning", "tool-calling"],
    representations: [{ artifact: "text", format: "markdown" }],
    execution: { result: "immediate", streaming: true },
    tools: { appTools: true, nativeTools: ["web-search"] },
    reasoning: { supported: true, controls: ["thinking"] },
    continuation: { mode: "none" },
    limits: { contextTokens: 1_000_000 },
    billingClass: "standard",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/anthropic/claude-sonnet-5/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/anthropic/claude-sonnet-5/"
    ),
  },
  {
    key: "google/gemini-3.7-flash",
    upstreamModelId: "google/gemini-3.7-flash",
    name: "Gemini 3.7 Flash",
    provider: "google",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "chat-completions",
    lifecycle: "launch",
    roles: ["balanced", "fast"],
    inputs: ["text", "image"],
    outputs: ["text"],
    capabilities: ["chat", "reasoning", "vision"],
    representations: [{ artifact: "text", format: "markdown" }],
    execution: { result: "immediate", streaming: true },
    reasoning: { supported: true },
    continuation: { mode: "none" },
    limits: { contextTokens: 1_048_576 },
    billingClass: "standard",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/google/gemini-3.7-flash/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/google/gemini-3.7-flash/"
    ),
  },
  {
    key: "@cf/zai-org/glm-4.7-flash",
    upstreamModelId: "@cf/zai-org/glm-4.7-flash",
    name: "GLM 4.7 Flash",
    provider: "zai-org",
    catalogSource: "workers-ai",
    transport: "workers-binding",
    protocol: "workers-ai",
    lifecycle: "legacy",
    roles: ["fast", "value", "workers-hosted"],
    inputs: ["text"],
    outputs: ["text"],
    capabilities: ["chat", "tool-calling"],
    representations: [{ artifact: "text", format: "markdown" }],
    execution: { result: "immediate", streaming: true },
    tools: { appTools: true },
    continuation: { mode: "none" },
    billingClass: "free",
    accessClass: "public",
    zeroDataRetention: "unknown",
    parameterSchemaRef:
      "https://developers.cloudflare.com/workers-ai/models/glm-4.7-flash/",
    verification: verified(
      "https://developers.cloudflare.com/workers-ai/models/glm-4.7-flash/"
    ),
  },
  {
    key: "@cf/zai-org/glm-5.3",
    upstreamModelId: "@cf/zai-org/glm-5.3",
    name: "GLM 5.3",
    provider: "zai-org",
    catalogSource: "workers-ai",
    transport: "workers-binding",
    protocol: "workers-ai",
    lifecycle: "experimental",
    roles: ["frontier", "workers-hosted"],
    inputs: ["text"],
    outputs: ["text"],
    capabilities: ["chat", "reasoning", "tool-calling", "structured-output"],
    representations: [{ artifact: "text", format: "markdown" }],
    execution: { result: "immediate", streaming: true },
    tools: { appTools: true },
    reasoning: { supported: true },
    continuation: { mode: "none" },
    limits: { contextTokens: 1_048_576 },
    billingClass: "premium",
    accessClass: "public",
    zeroDataRetention: "unknown",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/%40cf/zai-org/glm-5.3/"
    ),
  },
  {
    key: "@cf/deepseek-ai/deepseek-v4-pro-0813",
    upstreamModelId: "@cf/deepseek-ai/deepseek-v4-pro-0813",
    name: "DeepSeek V4 Pro",
    provider: "deepseek-ai",
    catalogSource: "workers-ai",
    transport: "workers-binding",
    protocol: "workers-ai",
    lifecycle: "experimental",
    roles: ["frontier", "workers-hosted"],
    inputs: ["text"],
    outputs: ["text"],
    capabilities: ["chat", "reasoning"],
    representations: [{ artifact: "text", format: "markdown" }],
    execution: { result: "immediate", streaming: true },
    reasoning: { supported: true },
    continuation: { mode: "none" },
    limits: { contextTokens: 1_048_576 },
    billingClass: "premium",
    accessClass: "public",
    zeroDataRetention: "unknown",
    verification: verified(
      "https://developers.cloudflare.com/workers-ai/models/"
    ),
  },
  {
    key: "@cf/deepseek-ai/deepseek-v4-flash-0731",
    upstreamModelId: "@cf/deepseek-ai/deepseek-v4-flash-0731",
    name: "DeepSeek V4 Flash",
    provider: "deepseek-ai",
    catalogSource: "workers-ai",
    transport: "workers-binding",
    protocol: "workers-ai",
    lifecycle: "experimental",
    roles: ["fast", "value", "workers-hosted"],
    inputs: ["text"],
    outputs: ["text"],
    capabilities: ["chat", "reasoning"],
    representations: [{ artifact: "text", format: "markdown" }],
    execution: { result: "immediate", streaming: true },
    reasoning: { supported: true },
    continuation: { mode: "none" },
    limits: { contextTokens: 1_048_576 },
    billingClass: "value",
    accessClass: "public",
    zeroDataRetention: "unknown",
    verification: verified(
      "https://developers.cloudflare.com/workers-ai/models/"
    ),
  },

  // Document / OCR specialists ----------------------------------------------
  {
    key: "@cf/moondream/moondream3.1-9B-A2B",
    upstreamModelId: "@cf/moondream/moondream3.1-9B-A2B",
    name: "Moondream 3.1",
    provider: "moondream",
    catalogSource: "workers-ai",
    transport: "workers-binding",
    protocol: "workers-ai",
    lifecycle: "launch",
    roles: ["specialist", "workers-hosted"],
    inputs: ["image"],
    outputs: ["text"],
    capabilities: [
      "vision",
      "reasoning",
      "ocr",
      "image-captioning",
      "object-detection",
      "structured-output",
    ],
    representations: [
      { artifact: "text", format: "plain" },
      { artifact: "text", format: "structured" },
    ],
    execution: { result: "immediate", streaming: true },
    reasoning: { supported: true },
    continuation: { mode: "none" },
    parameters: [
      {
        key: "task",
        label: "Vision task",
        kind: "select",
        options: [
          { value: "query", label: "Query" },
          { value: "caption", label: "Caption" },
          { value: "point", label: "Point" },
          { value: "detect", label: "Detect" },
        ],
        default: "query",
      },
    ],
    limits: { contextTokens: 32_768, maxOutputTokens: 28_672 },
    billingClass: "value",
    accessClass: "public",
    zeroDataRetention: "unknown",
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/%40cf/moondream/moondream3.1-9B-A2B/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/%40cf/moondream/moondream3.1-9B-A2B/"
    ),
  },
  {
    key: "fal-ai/got-ocr/v2",
    upstreamModelId: "fal-ai/got-ocr/v2",
    name: "GOT OCR 2.0",
    provider: "fal",
    catalogSource: "gateway-provider-native",
    transport: "gateway-provider-native",
    protocol: "provider-native",
    lifecycle: "launch",
    roles: ["specialist"],
    inputs: ["image"],
    outputs: ["text"],
    capabilities: ["ocr"],
    representations: [{ artifact: "text", format: "plain" }],
    execution: { result: "queued", streaming: false, background: true },
    continuation: { mode: "none" },
    billingClass: "standard",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    parameterSchemaRef: "https://fal.ai/models/fal-ai/got-ocr/v2/api",
    verification: verified(
      CLOUDFLARE_FAL_DOCS,
      "https://fal.ai/models/fal-ai/got-ocr/v2/api"
    ),
  },

  // Raster image generation / editing ---------------------------------------
  {
    key: "black-forest-labs/flux-2-max",
    upstreamModelId: "black-forest-labs/flux-2-max",
    name: "FLUX.2 Max",
    provider: "black-forest-labs",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "launch",
    roles: ["frontier", "editing"],
    inputs: ["text", "image"],
    outputs: ["image"],
    capabilities: [
      "image-generation",
      "image-edit",
      "image-multi-reference",
    ],
    representations: [
      {
        artifact: "image",
        format: "raster",
        mimeTypes: ["image/jpeg", "image/png", "image/webp"],
      },
    ],
    execution: { result: "immediate", streaming: false },
    continuation: { mode: "none" },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/black-forest-labs/flux-2-max/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/black-forest-labs/flux-2-max/"
    ),
  },
  {
    key: "openai/gpt-image-2",
    upstreamModelId: "openai/gpt-image-2",
    name: "GPT Image 2",
    provider: "openai",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "launch",
    roles: ["balanced", "editing"],
    inputs: ["text", "image"],
    outputs: ["image"],
    capabilities: [
      "image-generation",
      "image-edit",
      "image-multi-reference",
    ],
    representations: [
      {
        artifact: "image",
        format: "raster",
        mimeTypes: ["image/png", "image/webp", "image/jpeg"],
      },
    ],
    execution: { result: "immediate", streaming: false },
    continuation: { mode: "none" },
    parameters: [
      {
        key: "quality",
        label: "Quality",
        kind: "select",
        options: [
          { value: "auto", label: "Auto" },
          { value: "low", label: "Low" },
          { value: "medium", label: "Medium" },
          { value: "high", label: "High" },
        ],
        default: "auto",
      },
      {
        key: "output_format",
        label: "Format",
        kind: "select",
        options: [
          { value: "png", label: "PNG" },
          { value: "webp", label: "WebP" },
          { value: "jpeg", label: "JPEG" },
        ],
        default: "png",
      },
    ],
    limits: { maxReferences: 16 },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: true,
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/openai/gpt-image-2/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/openai/gpt-image-2/"
    ),
  },
  {
    key: "recraft/recraftv4-1-pro",
    upstreamModelId: "recraft/recraftv4-1-pro",
    name: "Recraft V4.1 Pro",
    provider: "recraft",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "launch",
    roles: ["design"],
    inputs: ["text"],
    outputs: ["image"],
    capabilities: ["image-generation"],
    representations: [
      {
        artifact: "image",
        format: "raster",
        mimeTypes: ["image/png", "image/jpeg", "image/webp"],
      },
    ],
    execution: { result: "immediate", streaming: false },
    continuation: { mode: "none" },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: true,
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/recraft/recraftv4-1-pro/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/recraft/recraftv4-1-pro/"
    ),
  },
  {
    key: "google/nano-banana-2",
    upstreamModelId: "google/nano-banana-2",
    name: "Nano Banana 2",
    provider: "google",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "launch",
    roles: ["balanced", "editing", "reference-heavy"],
    inputs: ["text", "image"],
    outputs: ["image"],
    capabilities: [
      "image-generation",
      "image-edit",
      "image-multi-reference",
    ],
    representations: [
      {
        artifact: "image",
        format: "raster",
        mimeTypes: ["image/png", "image/jpeg"],
      },
    ],
    execution: { result: "immediate", streaming: false },
    continuation: { mode: "none" },
    parameters: [
      {
        key: "resolution",
        label: "Resolution",
        kind: "select",
        options: [
          { value: "1K", label: "1K" },
          { value: "2K", label: "2K" },
          { value: "4K", label: "4K" },
        ],
        default: "1K",
      },
    ],
    limits: { maxReferences: 3 },
    billingClass: "standard",
    accessClass: "credential-required",
    zeroDataRetention: true,
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/google/nano-banana-2/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/google/nano-banana-2/"
    ),
  },
  {
    key: "ideogram/v4",
    upstreamModelId: "ideogram/v4",
    name: "Ideogram V4",
    provider: "fal",
    catalogSource: "gateway-provider-native",
    transport: "gateway-provider-native",
    protocol: "provider-native",
    lifecycle: "experimental",
    roles: ["design"],
    inputs: ["text"],
    outputs: ["image"],
    capabilities: ["image-generation"],
    representations: [
      {
        artifact: "image",
        format: "raster",
        mimeTypes: ["image/png", "image/jpeg", "image/webp"],
      },
    ],
    execution: { result: "either", streaming: true, background: true },
    continuation: { mode: "none" },
    billingClass: "standard",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    parameterSchemaRef: "https://fal.ai/models/ideogram/v4/api",
    verification: verified(
      CLOUDFLARE_FAL_DOCS,
      "https://fal.ai/models/ideogram/v4/api"
    ),
  },
  {
    key: "fal-ai/imageutils/rembg",
    upstreamModelId: "fal-ai/imageutils/rembg",
    name: "Rembg",
    provider: "fal",
    catalogSource: "gateway-provider-native",
    transport: "gateway-provider-native",
    protocol: "provider-native",
    lifecycle: "launch",
    roles: ["specialist"],
    inputs: ["image"],
    outputs: ["image"],
    capabilities: ["background-removal"],
    representations: [
      {
        artifact: "image",
        format: "raster",
        mimeTypes: ["image/png"],
        alpha: true,
      },
    ],
    execution: { result: "queued", streaming: false, background: true },
    continuation: { mode: "none" },
    billingClass: "value",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    parameterSchemaRef: "https://fal.ai/models/fal-ai/imageutils/rembg/api",
    verification: verified(
      CLOUDFLARE_FAL_DOCS,
      "https://fal.ai/models/fal-ai/imageutils/rembg/api"
    ),
  },
  {
    key: "black-forest-labs/flux-2-pro-preview",
    upstreamModelId: "black-forest-labs/flux-2-pro-preview",
    name: "FLUX.2 Pro",
    provider: "black-forest-labs",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "experimental",
    roles: ["editing"],
    inputs: ["text", "image"],
    outputs: ["image"],
    capabilities: [
      "image-generation",
      "image-edit",
      "image-multi-reference",
    ],
    representations: [{ artifact: "image", format: "raster" }],
    execution: { result: "immediate", streaming: false },
    continuation: { mode: "none" },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/black-forest-labs/flux-2-pro-preview/"
    ),
  },
  {
    key: "google/nano-banana-pro",
    upstreamModelId: "google/nano-banana-pro",
    name: "Nano Banana Pro",
    provider: "google",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "experimental",
    roles: ["frontier", "reference-heavy"],
    inputs: ["text", "image"],
    outputs: ["image"],
    capabilities: [
      "image-generation",
      "image-edit",
      "image-multi-reference",
    ],
    representations: [{ artifact: "image", format: "raster" }],
    execution: { result: "immediate", streaming: false },
    continuation: { mode: "none" },
    limits: { maxReferences: 3 },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: true,
    verification: verified(
      "https://developers.cloudflare.com/ai/models/google/nano-banana-pro/"
    ),
  },
  {
    key: "fal-ai/creative-upscaler",
    upstreamModelId: "fal-ai/creative-upscaler",
    name: "Creative Upscaler",
    provider: "fal",
    catalogSource: "gateway-provider-native",
    transport: "gateway-provider-native",
    protocol: "provider-native",
    lifecycle: "experimental",
    roles: ["specialist"],
    inputs: ["image"],
    outputs: ["image"],
    capabilities: ["upscale-creative"],
    representations: [{ artifact: "image", format: "raster" }],
    execution: { result: "queued", streaming: false, background: true },
    continuation: { mode: "none" },
    billingClass: "standard",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    verification: verified(
      CLOUDFLARE_FAL_DOCS,
      "https://fal.ai/models/fal-ai/creative-upscaler"
    ),
  },

  // SVG / vector --------------------------------------------------------------
  {
    key: "recraft/recraftv4-1-pro-vector",
    upstreamModelId: "recraft/recraftv4-1-pro-vector",
    name: "Recraft V4.1 Pro SVG",
    provider: "recraft",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "launch",
    roles: ["design", "frontier"],
    inputs: ["text"],
    outputs: ["image"],
    capabilities: ["svg-generation"],
    representations: [
      { artifact: "image", format: "svg", mimeTypes: ["image/svg+xml"] },
    ],
    execution: { result: "immediate", streaming: false },
    continuation: { mode: "none" },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: true,
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/recraft/recraftv4-1-pro-vector/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/recraft/recraftv4-1-pro-vector/"
    ),
  },
  {
    key: "recraft/recraftv4-1-vector",
    upstreamModelId: "recraft/recraftv4-1-vector",
    name: "Recraft V4.1 SVG",
    provider: "recraft",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "launch",
    roles: ["design", "value"],
    inputs: ["text"],
    outputs: ["image"],
    capabilities: ["svg-generation"],
    representations: [
      { artifact: "image", format: "svg", mimeTypes: ["image/svg+xml"] },
    ],
    execution: { result: "immediate", streaming: false },
    continuation: { mode: "none" },
    billingClass: "standard",
    accessClass: "credential-required",
    zeroDataRetention: true,
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/recraft/recraftv4-1-vector/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/recraft/recraftv4-1-vector/"
    ),
  },
  {
    key: "recraft/recraftv4-1-utility-pro-vector",
    upstreamModelId: "recraft/recraftv4-1-utility-pro-vector",
    name: "Recraft V4.1 Utility Pro SVG",
    provider: "recraft",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "experimental",
    roles: ["design"],
    inputs: ["text"],
    outputs: ["image"],
    capabilities: ["svg-generation"],
    representations: [{ artifact: "image", format: "svg" }],
    execution: { result: "immediate", streaming: false },
    continuation: { mode: "none" },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: true,
    verification: verified(
      "https://developers.cloudflare.com/ai/models/recraft/recraftv4-1-utility-pro-vector/"
    ),
  },

  // Speech -------------------------------------------------------------------
  {
    key: "xai/grok-stt",
    upstreamModelId: "xai/grok-stt",
    name: "Grok STT",
    provider: "xai",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "launch",
    roles: ["specialist"],
    inputs: ["audio"],
    outputs: ["text"],
    capabilities: [
      "transcription",
      "diarization",
      "speech-language-detection",
    ],
    representations: [{ artifact: "text", format: "transcript" }],
    execution: { result: "immediate", streaming: true },
    continuation: { mode: "none" },
    billingClass: "standard",
    accessClass: "credential-required",
    zeroDataRetention: true,
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/xai/grok-stt/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/xai/grok-stt/"
    ),
  },
  {
    key: "@cf/deepgram/nova-3",
    upstreamModelId: "@cf/deepgram/nova-3",
    name: "Deepgram Nova 3",
    provider: "deepgram",
    catalogSource: "workers-ai",
    transport: "workers-binding",
    protocol: "workers-ai",
    lifecycle: "launch",
    roles: ["specialist", "workers-hosted"],
    inputs: ["audio"],
    outputs: ["text"],
    capabilities: ["transcription", "diarization"],
    representations: [{ artifact: "text", format: "transcript" }],
    execution: { result: "immediate", streaming: true },
    continuation: { mode: "none" },
    billingClass: "value",
    accessClass: "public",
    zeroDataRetention: "unknown",
    parameterSchemaRef:
      "https://developers.cloudflare.com/workers-ai/models/nova-3/",
    verification: verified(
      "https://developers.cloudflare.com/workers-ai/models/nova-3/"
    ),
  },
  {
    key: "elevenlabs/eleven-v3",
    upstreamModelId: "elevenlabs/eleven-v3",
    name: "Eleven v3",
    provider: "elevenlabs",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "launch",
    roles: ["frontier", "specialist"],
    inputs: ["text"],
    outputs: ["audio"],
    capabilities: ["text-to-speech"],
    representations: [
      { artifact: "audio", format: "audio", containers: ["mp3", "wav"] },
    ],
    execution: { result: "immediate", streaming: false },
    continuation: { mode: "none" },
    identityInputs: ["builtin-voice"],
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/elevenlabs/eleven-v3/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/elevenlabs/eleven-v3/"
    ),
  },
  {
    key: "elevenlabs/eleven-flash-v2-5",
    upstreamModelId: "elevenlabs/eleven-flash-v2-5",
    name: "Eleven Flash v2.5",
    provider: "elevenlabs",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "launch",
    roles: ["fast", "specialist"],
    inputs: ["text"],
    outputs: ["audio"],
    capabilities: ["text-to-speech"],
    representations: [
      { artifact: "audio", format: "audio", containers: ["mp3", "wav"] },
    ],
    execution: { result: "immediate", streaming: false },
    continuation: { mode: "none" },
    identityInputs: ["builtin-voice"],
    billingClass: "standard",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/elevenlabs/eleven-flash-v2-5/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/elevenlabs/eleven-flash-v2-5/"
    ),
  },
  {
    key: "fal-ai/qwen-3-tts/clone-voice/1.7b",
    upstreamModelId: "fal-ai/qwen-3-tts/clone-voice/1.7b",
    name: "Qwen3 TTS Voice Clone",
    provider: "fal",
    catalogSource: "gateway-provider-native",
    transport: "gateway-provider-native",
    protocol: "provider-native",
    lifecycle: "experimental",
    roles: ["specialist"],
    inputs: ["audio"],
    outputs: [],
    capabilities: ["voice-cloning"],
    identityOutputs: ["cloned-voice"],
    execution: { result: "queued", streaming: false, background: true },
    continuation: { mode: "none" },
    billingClass: "standard",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    verification: verified(
      CLOUDFLARE_FAL_DOCS,
      "https://fal.ai/models/fal-ai/qwen-3-tts/clone-voice/1.7b"
    ),
  },

  // Post-launch audio / localization ----------------------------------------
  {
    key: "elevenlabs/music-v2",
    upstreamModelId: "elevenlabs/music-v2",
    name: "ElevenLabs Music v2",
    provider: "elevenlabs",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "experimental",
    roles: ["specialist"],
    inputs: ["text"],
    outputs: ["audio"],
    capabilities: ["music-generation"],
    representations: [{ artifact: "audio", format: "audio" }],
    execution: { result: "either", streaming: false, background: true },
    continuation: { mode: "none" },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/elevenlabs/music-v2/"
    ),
  },
  {
    key: "fal-ai/elevenlabs/sound-effects/v2",
    upstreamModelId: "fal-ai/elevenlabs/sound-effects/v2",
    name: "ElevenLabs Sound Effects v2",
    provider: "fal",
    catalogSource: "gateway-provider-native",
    transport: "gateway-provider-native",
    protocol: "provider-native",
    lifecycle: "experimental",
    roles: ["specialist"],
    inputs: ["text"],
    outputs: ["audio"],
    capabilities: ["sound-effect-generation"],
    representations: [{ artifact: "audio", format: "audio" }],
    execution: { result: "queued", streaming: false, background: true },
    continuation: { mode: "none" },
    billingClass: "standard",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    verification: verified(
      CLOUDFLARE_FAL_DOCS,
      "https://fal.ai/models/fal-ai/elevenlabs/sound-effects/v2"
    ),
  },
  {
    key: "fal-ai/elevenlabs/audio-isolation",
    upstreamModelId: "fal-ai/elevenlabs/audio-isolation",
    name: "ElevenLabs Audio Isolation",
    provider: "fal",
    catalogSource: "gateway-provider-native",
    transport: "gateway-provider-native",
    protocol: "provider-native",
    lifecycle: "experimental",
    roles: ["specialist"],
    inputs: ["audio"],
    outputs: ["audio"],
    capabilities: ["audio-isolation", "audio-to-audio"],
    representations: [{ artifact: "audio", format: "audio" }],
    execution: { result: "queued", streaming: false, background: true },
    continuation: { mode: "none" },
    billingClass: "standard",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    verification: verified(
      CLOUDFLARE_FAL_DOCS,
      "https://fal.ai/models/fal-ai/elevenlabs/audio-isolation"
    ),
  },
  {
    key: "fal-ai/elevenlabs/dubbing",
    upstreamModelId: "fal-ai/elevenlabs/dubbing",
    name: "ElevenLabs Dubbing",
    provider: "fal",
    catalogSource: "gateway-provider-native",
    transport: "gateway-provider-native",
    protocol: "provider-native",
    lifecycle: "experimental",
    roles: ["specialist"],
    inputs: ["audio", "video"],
    outputs: ["audio", "video"],
    capabilities: ["dubbing", "speaker-preservation"],
    representations: [
      { artifact: "audio", format: "audio" },
      { artifact: "video", format: "video", containers: ["mp4"] },
    ],
    execution: { result: "queued", streaming: false, background: true },
    continuation: { mode: "none" },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    verification: verified(
      CLOUDFLARE_FAL_DOCS,
      "https://fal.ai/models/fal-ai/elevenlabs/dubbing"
    ),
  },

  // Video --------------------------------------------------------------------
  {
    key: "google/veo-3.1-fast",
    upstreamModelId: "google/veo-3.1-fast",
    name: "Veo 3.1 Fast",
    provider: "google",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "launch",
    roles: ["fast", "balanced"],
    inputs: ["text", "image"],
    outputs: ["video"],
    capabilities: [
      "video-generation",
      "image-to-video",
      "native-video-audio",
    ],
    representations: [
      { artifact: "video", format: "video", containers: ["mp4"] },
    ],
    execution: { result: "either", streaming: false, background: true },
    continuation: { mode: "none" },
    parameters: [
      {
        key: "resolution",
        label: "Resolution",
        kind: "select",
        options: [
          { value: "720p", label: "720p" },
          { value: "1080p", label: "1080p" },
        ],
        default: "720p",
      },
      {
        key: "generate_audio",
        label: "Generate audio",
        kind: "boolean",
        default: true,
      },
    ],
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: true,
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/google/veo-3.1-fast/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/google/veo-3.1-fast/"
    ),
  },
  {
    key: "google/veo-3.1",
    upstreamModelId: "google/veo-3.1",
    name: "Veo 3.1",
    provider: "google",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "launch",
    roles: ["frontier"],
    inputs: ["text", "image"],
    outputs: ["video"],
    capabilities: [
      "video-generation",
      "image-to-video",
      "native-video-audio",
    ],
    representations: [
      { artifact: "video", format: "video", containers: ["mp4"] },
    ],
    execution: { result: "either", streaming: false, background: true },
    continuation: { mode: "none" },
    billingClass: "high-cost",
    accessClass: "credential-required",
    zeroDataRetention: true,
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/google/veo-3.1/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/google/veo-3.1/"
    ),
  },
  {
    key: "bytedance/seedance-2.5",
    upstreamModelId: "bytedance/seedance-2.5",
    name: "Seedance 2.5",
    provider: "bytedance",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "launch",
    roles: ["reference-heavy", "editing"],
    inputs: ["text", "image", "video", "audio"],
    outputs: ["video"],
    capabilities: [
      "video-generation",
      "image-to-video",
      "video-reference",
      "video-edit",
      "video-continuation",
      "video-first-frame",
      "video-last-frame",
      "video-multi-image-reference",
      "video-multi-video-reference",
      "video-audio-reference",
    ],
    representations: [
      { artifact: "video", format: "video", containers: ["mp4"] },
    ],
    execution: { result: "either", streaming: false, background: true },
    continuation: { mode: "none" },
    limits: { maxReferences: 50 },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/bytedance/seedance-2.5/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/bytedance/seedance-2.5/"
    ),
  },
  {
    key: "runwayml/aleph-2",
    upstreamModelId: "runwayml/aleph-2",
    name: "Runway Aleph 2",
    provider: "runwayml",
    catalogSource: "unified",
    transport: "unified-run",
    protocol: "unified-run",
    lifecycle: "launch",
    roles: ["editing", "specialist"],
    inputs: ["text", "video", "image"],
    outputs: ["video"],
    capabilities: ["video-edit", "video-reference"],
    representations: [
      { artifact: "video", format: "video", containers: ["mp4"] },
    ],
    execution: { result: "either", streaming: false, background: true },
    continuation: { mode: "none" },
    limits: { maxDurationSeconds: 30 },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    parameterSchemaRef:
      "https://developers.cloudflare.com/ai/models/runwayml/aleph-2/",
    verification: verified(
      "https://developers.cloudflare.com/ai/models/runwayml/aleph-2/"
    ),
  },
  ...[
    {
      key: "fal-ai/kling-video/o3/standard/text-to-video",
      name: "Kling O3 Standard Text to Video",
      inputs: ["text"] as const,
      capabilities: ["video-generation", "video-multi-shot", "native-video-audio"] as const,
      docs: "https://fal.ai/models/fal-ai/kling-video/o3/standard/text-to-video",
    },
    {
      key: "fal-ai/kling-video/o3/standard/image-to-video",
      name: "Kling O3 Standard Image to Video",
      inputs: ["text", "image"] as const,
      capabilities: [
        "video-generation",
        "image-to-video",
        "video-first-frame",
        "video-last-frame",
        "native-video-audio",
      ] as const,
      docs: "https://fal.ai/models/fal-ai/kling-video/o3/standard/image-to-video",
    },
    {
      key: "fal-ai/kling-video/o3/standard/reference-to-video",
      name: "Kling O3 Standard Reference to Video",
      inputs: ["text", "image", "video"] as const,
      capabilities: [
        "video-generation",
        "video-reference",
        "video-element-reference",
        "video-multi-shot",
        "native-video-audio",
      ] as const,
      docs: "https://fal.ai/models/fal-ai/kling-video/o3/standard/reference-to-video",
    },
    {
      key: "fal-ai/kling-video/o3/standard/video-to-video/reference",
      name: "Kling O3 Standard Video Reference",
      inputs: ["text", "video", "image"] as const,
      capabilities: ["video-reference", "video-edit", "video-element-reference"] as const,
      docs: "https://fal.ai/models/fal-ai/kling-video/o3/standard/video-to-video/reference",
    },
    {
      key: "fal-ai/kling-video/o3/standard/video-to-video/edit",
      name: "Kling O3 Standard Video Edit",
      inputs: ["text", "video"] as const,
      capabilities: ["video-edit"] as const,
      docs: "https://fal.ai/models/fal-ai/kling-video/o3/standard/video-to-video/edit",
    },
  ].map(({ key, name, inputs, capabilities, docs }) => ({
    key,
    upstreamModelId: key,
    name,
    provider: "fal",
    catalogSource: "gateway-provider-native" as const,
    transport: "gateway-provider-native" as const,
    protocol: "provider-native" as const,
    lifecycle: "launch" as const,
    roles: ["reference-heavy", "editing"] as const,
    inputs,
    outputs: ["video"] as const,
    capabilities,
    representations: [
      { artifact: "video" as const, format: "video" as const, containers: ["mp4"] },
    ],
    execution: { result: "queued" as const, streaming: false, background: true },
    continuation: { mode: "none" as const },
    billingClass: "premium" as const,
    accessClass: "credential-required" as const,
    zeroDataRetention: "unknown" as const,
    parameterSchemaRef: docs,
    verification: verified(CLOUDFLARE_FAL_DOCS, docs),
  })),

  // Experimental 3D ----------------------------------------------------------
  {
    key: "meshy/v7/text-to-3d",
    upstreamModelId: "meshy/v7/text-to-3d",
    name: "Meshy v7 Text to 3D",
    provider: "fal",
    catalogSource: "gateway-provider-native",
    transport: "gateway-provider-native",
    protocol: "provider-native",
    lifecycle: "experimental",
    roles: ["specialist"],
    inputs: ["text"],
    outputs: ["model3d"],
    capabilities: ["text-to-3d"],
    representations: [
      {
        artifact: "model3d",
        format: "model3d",
        containers: ["glb", "gltf", "obj"],
        materials: "pbr",
      },
    ],
    execution: { result: "queued", streaming: false, background: true },
    continuation: { mode: "none" },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    verification: verified(
      CLOUDFLARE_FAL_DOCS,
      "https://fal.ai/models/meshy/v7/text-to-3d"
    ),
  },
  {
    key: "fal-ai/hunyuan3d-v3/image-to-3d",
    upstreamModelId: "fal-ai/hunyuan3d-v3/image-to-3d",
    name: "Hunyuan3D v3 Image to 3D",
    provider: "fal",
    catalogSource: "gateway-provider-native",
    transport: "gateway-provider-native",
    protocol: "provider-native",
    lifecycle: "experimental",
    roles: ["specialist"],
    inputs: ["image"],
    outputs: ["model3d"],
    capabilities: ["image-to-3d"],
    representations: [
      {
        artifact: "model3d",
        format: "model3d",
        containers: ["glb", "obj"],
        materials: "pbr",
      },
    ],
    execution: { result: "queued", streaming: false, background: true },
    continuation: { mode: "none" },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    verification: verified(
      CLOUDFLARE_FAL_DOCS,
      "https://fal.ai/models/fal-ai/hunyuan3d-v3/image-to-3d"
    ),
  },
  {
    key: "fal-ai/meshy/rigging",
    upstreamModelId: "fal-ai/meshy/rigging",
    name: "Meshy Rigging",
    provider: "fal",
    catalogSource: "gateway-provider-native",
    transport: "gateway-provider-native",
    protocol: "provider-native",
    lifecycle: "experimental",
    roles: ["specialist"],
    inputs: ["model3d"],
    outputs: ["model3d"],
    capabilities: ["model3d-rigging"],
    representations: [
      {
        artifact: "model3d",
        format: "model3d",
        containers: ["fbx", "glb"],
        materials: "optional",
      },
    ],
    execution: { result: "queued", streaming: false, background: true },
    continuation: { mode: "none" },
    billingClass: "premium",
    accessClass: "credential-required",
    zeroDataRetention: "unknown",
    verification: verified(
      CLOUDFLARE_FAL_DOCS,
      "https://fal.ai/models/fal-ai/meshy/rigging"
    ),
  },
] as const satisfies readonly ModelDefinition[])

export const LAUNCH_MODEL_CATALOG = MODEL_CATALOG.filter(
  (model) => model.lifecycle === "launch"
)

export const WORKERS_AI_LAUNCH_MODEL_KEYS = LAUNCH_MODEL_CATALOG.filter(
  (model) => model.catalogSource === "workers-ai"
).map((model) => model.key)
